*** Number of time outs
*** Captain metrics
*** handler metrics
*** Defuser metrics
*** Team pair metrics
*** Waiting time,  post allocation and Execution time  per module
*** Number of Mistakes
*** Number of Abandoned Modules
*** User Stats per player / pair
*** Handler Stats
*** Module Level records
*** Time players spend waiting to be allocated a new task
*** Number of modules Completed
*** Times per module per player 
*** Emoji's / moods
*** Voting calls
*** Vote Share
*** HRV

Allocation of modules per team member graph, to show distribution of workload within group.
regardless of whatever the modules are, this data set will come out of the generic highlevel structure.
each module has its own timer, this timer does not start unless the pair picks and clicks on the module
this allows us to capture allocation / strategizing and execution time at a module level.
we should be able to compare these across rounds, pairs, teams and game plays

Allocation of modules per team member graph, to show distribution of workload within group.
regardless of whatever the modules are, this data set will come out of the generic highlevel structure.
each module has its own timer, this timer does not start unless the pair picks and clicks on the module
this allows us to capture allocation / strategizing and execution time at a module level.
we should be able to compare these across rounds, pairs, teams and game plays
